name: CI

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies
      - run: pip install antlr4-tools
      - run: pip install -r requirements.txt
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make
          version: 1.0
      - run: make
      - run: python3 ./test.py